export { default as feature1 } from './feature1.png'
export { default as feature2 } from './feature2.png'
export { default as feature3 } from './feature3.png'
export { default as macbook } from './macbook.png'
export { default as penHolder } from './penHolder.png'
export { default as earphones } from './earphones.png'
export { default as logo } from './logo.svg'
export { default as iconMail } from './icon-mail.png'